spring:
  server:
    port: 8394
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
api:
    security:
      token:
        secret: ${JWT_SECRET:my-secret-key}
